SELECT ROW_NUMBER() OVER (PARTITION BY 1) AS N, CNT, YYYY_MM, 1 AS DataSet FROM (
SELECT YYYY_MM, COUNT(*) AS CNT FROM (

SELECT ApplicationId, Name, StartDate, CAST(CAST(EXTRACT(YEAR FROM StartDate) AS INT) AS TEXT) || '-' || CASE WHEN CAST(EXTRACT(MONTH FROM StartDate) AS INT) < 10 THEN '0' ELSE '' END || CAST(CAST(EXTRACT(MONTH FROM StartDate) AS INT) AS TEXT) AS YYYY_MM
FROM AuthDB_Applications
WHERE ApplicationId NOT IN (SELECT ApplicationId FROM EventCube.TestEvents)
AND StartDate < '2015-06-30'
AND StartDate IS NOT NULL
AND StartDate >= CAST(CAST(CAST(EXTRACT(YEAR FROM CURRENT_DATE - INTERVAL'13 months') AS INT) AS TEXT) || '-' || CASE WHEN CAST(EXTRACT(MONTH FROM CURRENT_DATE- INTERVAL'13 months') AS INT) < 10 THEN '0' ELSE '' END || CAST(CAST(EXTRACT(MONTH FROM CURRENT_DATE- INTERVAL'13 months') AS INT) AS TEXT) || '-01' AS DATE)

) t GROUP BY 1 ORDER BY 1
) t