--Active Users per Month
SELECT 
'Active Users per Month' AS Label,
EXTRACT(YEAR FROM FirstTimestamp) || '-' || CASE WHEN CAST(EXTRACT(MONTH FROM FirstTimestamp) AS INT) < 10 THEN '0' ELSE '' END || EXTRACT(MONTH FROM FirstTimestamp) AS YYYY_MM,
COUNT(*) AS CNT
FROM EventCube.Agg_Session_Per_AppUser 
WHERE FirstTimestamp >= CAST(EXTRACT(YEAR FROM CURRENT_DATE - INTERVAL'13 Months') || '-' || CASE WHEN CAST(EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL'13 Months') AS INT) < 10 THEN '0' ELSE '' END || EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL'13 Months') || '-01 00:00:00' AS TIMESTAMP) 
AND FirstTimestamp < CAST(EXTRACT(YEAR FROM CURRENT_DATE - INTERVAL'0 Months') || '-' || CASE WHEN CAST(EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL'0 Months') AS INT) < 10 THEN '0' ELSE '' END || EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL'0 Months') || '-01 00:00:00' AS TIMESTAMP)
GROUP BY 1,2 ORDER BY 1,2;